// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbK3qmZnEoOqhGirJg1zdqy1K0FxC43aE',
    appId: '1:522151808185:web:a41228d2b3849246d81f68',
    messagingSenderId: '522151808185',
    projectId: 'hostel-dbc9c',
    authDomain: 'hostel-dbc9c.firebaseapp.com',
    storageBucket: 'hostel-dbc9c.appspot.com',
    measurementId: 'G-8NXNVHNGZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7HWmF9lM-mKAvqmMD2Wm6-yQuDFuzpDk',
    appId: '1:522151808185:android:f1f87c196d8eb640d81f68',
    messagingSenderId: '522151808185',
    projectId: 'hostel-dbc9c',
    storageBucket: 'hostel-dbc9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWoMoE3TpyYStwqJS3CK3hDJm_JfyTrSs',
    appId: '1:522151808185:ios:ce249435b579dfb6d81f68',
    messagingSenderId: '522151808185',
    projectId: 'hostel-dbc9c',
    storageBucket: 'hostel-dbc9c.appspot.com',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWoMoE3TpyYStwqJS3CK3hDJm_JfyTrSs',
    appId: '1:522151808185:ios:ce249435b579dfb6d81f68',
    messagingSenderId: '522151808185',
    projectId: 'hostel-dbc9c',
    storageBucket: 'hostel-dbc9c.appspot.com',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbK3qmZnEoOqhGirJg1zdqy1K0FxC43aE',
    appId: '1:522151808185:web:489f6f494ba8744fd81f68',
    messagingSenderId: '522151808185',
    projectId: 'hostel-dbc9c',
    authDomain: 'hostel-dbc9c.firebaseapp.com',
    storageBucket: 'hostel-dbc9c.appspot.com',
    measurementId: 'G-0Q3T8S75BB',
  );
}
